"""
WardenStrike - Report Generator
Multi-format reporting: Markdown, HTML, JSON.
Platform-specific templates: HackerOne, Bugcrowd, Intigriti, Immunefi.
"""

import json
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, BaseLoader

from wardenstrike.config import Config
from wardenstrike.core.session import SessionManager, Finding, Engagement
from wardenstrike.core.ai_engine import AIEngine
from wardenstrike.utils.logger import get_logger

log = get_logger("reporting")


# --- Embedded Templates (fallback when template files don't exist) ---

MARKDOWN_TEMPLATE = """# {{ title }}

**Date:** {{ date }}
**Platform:** {{ platform | upper }}
**Severity:** {{ severity | upper }}
{% if cvss_score %}**CVSS Score:** {{ cvss_score }} ({{ cvss_vector }}){% endif %}
{% if cwe_id %}**CWE:** {{ cwe_id }}{% endif %}

---

## Summary

{{ description }}

## Affected Asset

- **URL:** `{{ url }}`
{% if endpoint %}- **Endpoint:** `{{ endpoint }}`{% endif %}
{% if method %}- **Method:** {{ method }}{% endif %}
{% if parameter %}- **Parameter:** `{{ parameter }}`{% endif %}

## Steps to Reproduce

{% for step in steps %}
{{ loop.index }}. {{ step }}
{% endfor %}

{% if payload %}
## Payload

```
{{ payload }}
```
{% endif %}

{% if request %}
## HTTP Request

```http
{{ request }}
```
{% endif %}

{% if response %}
## HTTP Response (Relevant Part)

```http
{{ response }}
```
{% endif %}

{% if evidence %}
## Evidence

{{ evidence }}
{% endif %}

## Impact

{{ impact }}

## Remediation

{{ remediation }}

{% if references %}
## References

{% for ref in references %}
- {{ ref }}
{% endfor %}
{% endif %}

---
*Generated by WardenStrike v1.0.0*
"""

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Security Report</title>
    <style>
        :root { --bg: #0d1117; --fg: #c9d1d9; --accent: #58a6ff; --border: #30363d;
                --critical: #f85149; --high: #f0883e; --medium: #d29922; --low: #3fb950; --info: #58a6ff; }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', monospace;
               background: var(--bg); color: var(--fg); line-height: 1.6; padding: 2rem; max-width: 900px; margin: auto; }
        h1 { color: var(--accent); border-bottom: 2px solid var(--border); padding-bottom: .5rem; margin-bottom: 1rem; }
        h2 { color: var(--accent); margin: 1.5rem 0 .5rem; font-size: 1.2rem; }
        .meta { background: #161b22; border: 1px solid var(--border); border-radius: 6px; padding: 1rem; margin: 1rem 0; }
        .meta span { display: inline-block; margin-right: 2rem; }
        .severity { padding: 2px 10px; border-radius: 12px; font-weight: bold; color: #fff; font-size: .85rem; }
        .severity.critical { background: var(--critical); }
        .severity.high { background: var(--high); }
        .severity.medium { background: var(--medium); }
        .severity.low { background: var(--low); }
        .severity.info { background: var(--info); }
        pre { background: #161b22; border: 1px solid var(--border); border-radius: 6px;
              padding: 1rem; overflow-x: auto; font-size: .85rem; margin: .5rem 0; }
        code { font-family: 'Fira Code', 'Courier New', monospace; }
        ol, ul { padding-left: 1.5rem; margin: .5rem 0; }
        li { margin: .3rem 0; }
        a { color: var(--accent); }
        .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border);
                  font-size: .8rem; color: #484f58; }
    </style>
</head>
<body>
    <h1>{{ title }}</h1>
    <div class="meta">
        <span><strong>Date:</strong> {{ date }}</span>
        <span><strong>Platform:</strong> {{ platform | upper }}</span>
        <span><strong>Severity:</strong> <span class="severity {{ severity }}">{{ severity | upper }}</span></span>
        {% if cvss_score %}<span><strong>CVSS:</strong> {{ cvss_score }}</span>{% endif %}
        {% if cwe_id %}<span><strong>CWE:</strong> {{ cwe_id }}</span>{% endif %}
    </div>

    <h2>Summary</h2>
    <p>{{ description }}</p>

    <h2>Affected Asset</h2>
    <ul>
        <li><strong>URL:</strong> <code>{{ url }}</code></li>
        {% if endpoint %}<li><strong>Endpoint:</strong> <code>{{ endpoint }}</code></li>{% endif %}
        {% if method %}<li><strong>Method:</strong> {{ method }}</li>{% endif %}
        {% if parameter %}<li><strong>Parameter:</strong> <code>{{ parameter }}</code></li>{% endif %}
    </ul>

    <h2>Steps to Reproduce</h2>
    <ol>
        {% for step in steps %}
        <li>{{ step }}</li>
        {% endfor %}
    </ol>

    {% if payload %}
    <h2>Payload</h2>
    <pre><code>{{ payload }}</code></pre>
    {% endif %}

    {% if request %}
    <h2>HTTP Request</h2>
    <pre><code>{{ request }}</code></pre>
    {% endif %}

    {% if evidence %}
    <h2>Evidence</h2>
    <p>{{ evidence }}</p>
    {% endif %}

    <h2>Impact</h2>
    <p>{{ impact }}</p>

    <h2>Remediation</h2>
    <p>{{ remediation }}</p>

    {% if references %}
    <h2>References</h2>
    <ul>
        {% for ref in references %}
        <li><a href="{{ ref }}">{{ ref }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="footer">Generated by WardenStrike v1.0.0 | {{ date }}</div>
</body>
</html>
"""


class ReportGenerator:
    """Multi-format security report generator."""

    def __init__(self, config: Config, db: SessionManager, ai: AIEngine | None = None):
        self.config = config
        self.db = db
        self.ai = ai
        self.output_dir = Path(config.get("reporting", "output_dir", default="./reports"))
        self.output_dir.mkdir(parents=True, exist_ok=True)

        templates_dir = config.get("reporting", "templates_dir", default="")
        if templates_dir and Path(templates_dir).exists():
            self.env = Environment(loader=FileSystemLoader(templates_dir))
        else:
            self.env = Environment(loader=BaseLoader())

    def generate(self, finding_id: int, formats: list[str] | None = None, platform: str | None = None) -> dict[str, str]:
        """Generate reports for a finding in specified formats."""
        with self.db.get_session() as session:
            finding = session.query(Finding).get(finding_id)
            if not finding:
                raise ValueError(f"Finding {finding_id} not found")

            engagement = session.query(Engagement).get(finding.engagement_id)
            platform = platform or self.config.get("reporting", "platform", default="hackerone")
            formats = formats or self.config.get("reporting", "formats", default=["markdown"])

            # Build template context
            context = self._build_context(finding, engagement, platform)

            # If we have AI and the finding lacks description/impact, generate them
            if self.ai and (not finding.description or not finding.impact):
                ai_report = self.ai.generate_report(context, platform)
                context["ai_generated_report"] = ai_report

            outputs = {}
            for fmt in formats:
                output_path = self._generate_format(context, fmt, finding)
                if output_path:
                    outputs[fmt] = output_path

            return outputs

    def generate_executive_summary(self, engagement_id: int) -> str:
        """Generate an executive summary for all findings in an engagement."""
        with self.db.get_session() as session:
            engagement = session.query(Engagement).get(engagement_id)
            findings = session.query(Finding).filter_by(
                engagement_id=engagement_id
            ).filter(
                Finding.status.in_(["confirmed", "reported"])
            ).all()

            if not findings:
                return "No confirmed findings to report."

            stats = self.db.get_finding_stats(engagement_id)

            summary = f"""# Executive Summary - {engagement.name}

**Date:** {datetime.now().strftime('%Y-%m-%d')}
**Platform:** {engagement.platform or 'N/A'}
**Total Findings:** {stats['total']}

## Severity Distribution

| Severity | Count |
|----------|-------|
"""
            for sev in ["critical", "high", "medium", "low", "info"]:
                count = stats["by_severity"].get(sev, 0)
                if count > 0:
                    summary += f"| {sev.upper()} | {count} |\n"

            summary += "\n## Findings Overview\n\n"
            for f in findings:
                summary += f"### {f.severity.upper()}: {f.title}\n"
                summary += f"- **Type:** {f.vuln_type}\n"
                summary += f"- **URL:** {f.url or 'N/A'}\n"
                if f.cvss_score:
                    summary += f"- **CVSS:** {f.cvss_score}\n"
                summary += "\n"

            summary += "\n---\n*Generated by WardenStrike v1.0.0*\n"

            output_path = self.output_dir / f"executive_summary_{engagement.name}_{datetime.now().strftime('%Y%m%d')}.md"
            output_path.write_text(summary)
            log.success(f"Executive summary: {output_path}")
            return str(output_path)

    def _build_context(self, finding: Finding, engagement: Engagement | None, platform: str) -> dict:
        """Build the template rendering context."""
        steps = []
        if finding.steps_to_reproduce:
            try:
                steps = json.loads(finding.steps_to_reproduce)
            except (json.JSONDecodeError, TypeError):
                steps = [finding.steps_to_reproduce]

        references = []
        if finding.references:
            try:
                references = json.loads(finding.references)
            except (json.JSONDecodeError, TypeError):
                references = [finding.references]

        return {
            "title": finding.title,
            "vuln_type": finding.vuln_type,
            "severity": finding.severity or "medium",
            "cvss_score": finding.cvss_score,
            "cvss_vector": finding.cvss_vector,
            "cwe_id": finding.cwe_id,
            "url": finding.url or "",
            "endpoint": finding.endpoint or "",
            "method": finding.method or "",
            "parameter": finding.parameter or "",
            "payload": finding.payload or "",
            "evidence": finding.evidence or "",
            "request": finding.request or "",
            "response": finding.response or "",
            "description": finding.description or f"A {finding.vuln_type} vulnerability was identified.",
            "impact": finding.impact or "",
            "remediation": finding.remediation or "",
            "steps": steps or [f"Navigate to {finding.url}", "Observe the vulnerability"],
            "references": references,
            "platform": platform,
            "date": datetime.now().strftime("%Y-%m-%d"),
            "engagement": engagement.name if engagement else "",
            "tool_source": finding.tool_source or "",
        }

    def _generate_format(self, context: dict, fmt: str, finding: Finding) -> str | None:
        """Generate a report in a specific format."""
        safe_title = "".join(c if c.isalnum() or c in "-_" else "_" for c in finding.title[:60])
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        if fmt == "markdown":
            template = self.env.from_string(MARKDOWN_TEMPLATE)
            content = template.render(**context)
            path = self.output_dir / f"{safe_title}_{timestamp}.md"
            path.write_text(content)
            log.success(f"Markdown report: {path}")
            return str(path)

        elif fmt == "html":
            template = self.env.from_string(HTML_TEMPLATE)
            content = template.render(**context)
            path = self.output_dir / f"{safe_title}_{timestamp}.html"
            path.write_text(content)
            log.success(f"HTML report: {path}")
            return str(path)

        elif fmt == "json":
            path = self.output_dir / f"{safe_title}_{timestamp}.json"
            path.write_text(json.dumps(context, indent=2, default=str))
            log.success(f"JSON report: {path}")
            return str(path)

        elif fmt == "ai":
            # Full AI-generated report
            if self.ai:
                report = self.ai.generate_report(context, context.get("platform", "hackerone"))
                path = self.output_dir / f"{safe_title}_{timestamp}_ai.md"
                path.write_text(report)
                log.success(f"AI report: {path}")
                return str(path)

        return None
